<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!--<TargetFrameworks>net35;net40;net45;net47;netcoreapp3.0;netcoreapp3.1;net5.0-windows;net6.0-windows;net10.0-windows</TargetFrameworks>-->
    <TargetFrameworks>net45;netcoreapp3.1;net10.0-windows</TargetFrameworks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>KGySoft</RootNamespace>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\KGySoft.snk</AssemblyOriginatorKeyFile>
    <!--<RunCodeAnalysis>true</RunCodeAnalysis>-->
    <CodeAnalysisRuleSet>..\KGySoft.WinForms.ruleset</CodeAnalysisRuleSet>
    <LangVersion>latest</LangVersion>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.102">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="HelpOut\**" />
    <None Include="..\LICENSE" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".nuspec\KGySoft.WinForms.nuspec" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="KGySoft.Drawing" Version="10.0.1" />
  </ItemGroup>

  <!-- .NET Framework only references -->
  <ItemGroup Condition="'$(TargetFramework)'=='net35' OR '$(TargetFramework)'=='net40' OR '$(TargetFramework)'=='net45' OR '$(TargetFramework)'=='net47'">
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Design" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="WinForms\Controls\Resources\Toolbox.AdvancedLabel.png" />
    <EmbeddedResource Include="WinForms\Controls\Resources\Toolbox.AdvancedPanel.png" />
    <EmbeddedResource Include="WinForms\Controls\Resources\Toolbox.AdvancedTextBox.png" />
    <EmbeddedResource Include="WinForms\Controls\Resources\Toolbox.CheckGroupBox.png" />
    <EmbeddedResource Include="WinForms\Controls\Resources\Toolbox.CommandLinkButton.png" />
    <EmbeddedResource Include="WinForms\Controls\Resources\Toolbox.DecimalTextBox.png" />
    <EmbeddedResource Include="WinForms\Controls\Resources\Toolbox.OkCancelButtons.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="KGySoft.WinForms.Messages.resx">
      <LogicalName>KGySoft.WinForms.Messages.resources</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>