<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <TargetFrameworks>net35;net40;net45;netcoreapp3.0</TargetFrameworks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>KGySoft.WinForms</RootNamespace>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\KGySoft.snk</AssemblyOriginatorKeyFile>
    <!--<RunCodeAnalysis>true</RunCodeAnalysis>-->
    <!--<CodeAnalysisRuleSet>KGySoft.WinForms.ruleset</CodeAnalysisRuleSet>-->
    <LangVersion>latest</LangVersion>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="HelpOut\**" />
    <None Include="..\LICENSE"/>
  </ItemGroup>

  <ItemGroup>
    <None Include=".nuspec\readme.txt" />
    <None Include=".nuspec\KGySoft.WinForms.nuspec" />
    <None Include=".nuspec\readme.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="KGySoft.CoreLibraries" Version="5.1.1" />
    <PackageReference Include="KGySoft.Drawing" Version="5.1.0" />
    <!--<PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.9.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>-->
  </ItemGroup>

  <!-- .NET Framework only references -->
  <ItemGroup Condition="'$(TargetFramework)'=='net35' OR '$(TargetFramework)'=='net40' OR '$(TargetFramework)'=='net45'">
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Design" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Interop\**" />
    <EmbeddedResource Remove="Interop\**" />
    <None Remove="Interop\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Folder Include=".nuspec\" />
  </ItemGroup>

</Project>