<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!--<TargetFrameworks>net35;net40;netcoreapp3.0;net7.0-windows</TargetFrameworks>-->
    <TargetFrameworks>net35;net40;netcoreapp3.0;net7.0-windows;net9.0-windows</TargetFrameworks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>KGySoft.WinForms</RootNamespace>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\KGySoft.snk</AssemblyOriginatorKeyFile>
    <!--<RunCodeAnalysis>true</RunCodeAnalysis>-->
    <!--<CodeAnalysisRuleSet>KGySoft.WinForms.ruleset</CodeAnalysisRuleSet>-->
    <LangVersion>latest</LangVersion>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <NoWarn>$(NoWarn);WFO1000</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="HelpOut\**" />
    <None Include="..\LICENSE" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".nuspec\readme.txt" />
    <None Include=".nuspec\KGySoft.WinForms.nuspec" />
    <None Include=".nuspec\readme.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="KGySoft.Drawing" Version="9.2.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <!-- .NET Framework only references -->
  <ItemGroup Condition="'$(TargetFramework)'=='net35' OR '$(TargetFramework)'=='net40' OR '$(TargetFramework)'=='net45'">
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Design" />
  </ItemGroup>

  <!--TODO: remove content-->
  <ItemGroup>
    <Compile Remove="Interop\**" />
    <EmbeddedResource Remove="Interop\**" />
    <None Remove="Interop\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Controls\Resources\Toolbox.AdvancedLabel.png" />
    <EmbeddedResource Include="Controls\Resources\Toolbox.CommandLinkButton.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="KGySoft.WinForms.Messages.resx">
      <LogicalName>KGySoft.WinForms.Messages.resources</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>